CREATE TABLE import_devis (
    couleur VARCHAR(20),
    dossier TEXT,
    date_devis DATE,
    patient VARCHAR(255),
    mutuelle VARCHAR(255),
    patient_c2s VARCHAR(5),
    montant NUMERIC(10, 2),
    devis_signe VARCHAR(5),
    praticien VARCHAR(50),
    observation TEXT,
    date_envoi_pec DATE,
    date_fin_validite_pec DATE,
    part_secu NUMERIC(10, 2),
    part_mutuelle NUMERIC(10, 2),
    part_rac NUMERIC(10, 2),
    date_paiement_cb_ou_esp DATE,
    date_depot_chq_pec DATE,
    date_depot_chq_part_mut DATE,
    date_depot_chq_rac DATE,
    date_taille_empreinte DATE,
    retour_labo TEXT,
    travail_pose TEXT,
    date_1er_appel DATE,
    note_1er_appel TEXT,
    date_2eme_appel DATE,
    note_2eme_appel TEXT,
    date_3eme_appel DATE,
    note_3eme_appel TEXT,
    date_envoi_de_mail DATE
);
